[project]
name = "btc-backed-lending"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.btc-lending]
path = "contracts/btc-lending.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
